// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syjxtyvsencbmhuprnyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5anh0eXZzZW5jYm1odXBybnl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzQ4MTQsImV4cCI6MjA2NTc1MDgxNH0.0MchabnLmc3rnXzHnKeTYJO-gTDV3MzYNQQOl3ARCnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});